backend:
  name: github
  repo: https://github.com/uscana/fitweb.git # Ganti dengan path repo GitHub Anda
  branch: main # Atau 'master' tergantung branch default Anda

media_folder: "public/images" # Tempat menyimpan file/gambar yang di-upload
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog" # Sesuaikan dengan folder penyimpanan artikel di project Anda
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
